import Link from 'next/link';

export default async function TermsOfService() {
  return (
    <div className='px-10 py-5 text-neutral-black flex flex-col gap-3'>
      <h1 className='font-bold text-3xl lg:text-5xl'>
        Terms of Use for Howcan, Inc.
      </h1>
      <p className='font-bold mt-5 lg:mt-10'>
        Last Updated:{' '}
        <span className='opacity-80'>
          {new Date(Date.now()).toLocaleString().split(',')[0]}
        </span>
      </p>
      <h3 className='font-bold text-xl lg:text-2xl'>Introduction</h3>
      <p className='opacity-80 font-medium'>
        Welcome to Howcan, Inc. (&quot;we&quot;, &quot;our&quot;, or
        &quot;us&quot;). We operate the website Howcan.io and offer a service
        that creates cooking recipes and other personalized information. By
        using our website and services, you agree to comply with and be bound by
        these Terms of Use.
      </p>
      <h3 className='font-bold text-xl lg:text-2xl'> User Conduct</h3>
      <p className='opacity-80 font-medium'>
        Our service is designed to simplify your life by creating recipes based
        on a user&apos;s inquiry. While we encourage productive and respectful
        use of our service, you are prohibited from engaging in the following
        types of content or behavior:
      </p>
      <ul className='list-disc pl-6'>
        <li>Pornographic or violent content</li>
        <li>Hate speech or discrimination</li>
        <li>Harassment and bullying</li>
        <li>Spam or unsolicited promotions</li>
        <li>Fraudulent or misleading content</li>
        <li>Intellectual property violations</li>
        <li>Illegal activities</li>
        <li>Sharing personal or confidential information without consent</li>
        <li>Distributing malicious software</li>
        <li>Unauthorized commercial activities</li>
        <li>Impersonation of others</li>
        <li>Trolling or provocation</li>
        <li>Excessive profanity</li>
        <li>Adult content not suitable for a general audience</li>
        <li>Promotion of self-harm or harm to others</li>
        <li>Political or religious extremism</li>
      </ul>
      <h3 className='font-bold text-xl lg:text-2xl'>
        Accuracy of Results Pages
      </h3>
      <p className='opacity-80 font-medium'>
        We use AI technologies, including services like ChatGPT 3.5 and ChatGPT
        4, to help generate recipes and other personalized result pages. While
        we aim for this information to be accurate and helpful, it&apos;s
        important to understand that inaccuracies can occur.
      </p>
      <h3 className='font-bold text-xl lg:text-2xl'>Content Ownership</h3>
      <p className='opacity-80 font-medium'>
        To the fullest extent permitted by applicable law, all summaries
        generated by our service are the property of Howcan, Inc
      </p>
      <h3 className='font-bold text-xl lg:text-2xl'>User-Generated Content</h3>
      <p className='opacity-80 font-medium'>
        If our service allows for user-generated content, you are solely
        responsible for the content you post and the consequences thereof.
      </p>
      <h3 className='font-bold text-xl lg:text-2xl'>Dispute Resolution</h3>
      <p className='opacity-80 font-medium'>
        Any disputes arising out of or relating to these Terms of Use or your
        use of our service shall be resolved through arbitration in New York,
        under the rules of the American Arbitration Association.
      </p>
      <h3 className='font-bold text-xl lg:text-2xl'>Governing Law</h3>
      <p className='opacity-80 font-medium'>
        These Terms of Use are governed by the laws of the State of New York,
        without regard to its conflict of law principles.
      </p>
      <h3 className='font-bold text-xl lg:text-2xl'>Termination</h3>
      <p className='opacity-80 font-medium'>
        We reserve the sole and final right to terminate your account for any
        reason. If you wish to appeal a termination, you may email
        <span className='text-primary'>
          <Link href='mailto:support@howcan.io'>{''} support@howcan.io</Link>
        </span>{' '}
        and include any supporting documents.
      </p>
      <h3 className='font-bold text-xl lg:text-2xl'>Limitation of Liability</h3>
      <p className='opacity-80 font-medium'>
        To the fullest extent permitted by applicable law, Howcan, Inc. shall
        not be liable for any indirect, incidental, special, consequential, or
        punitive damages, or any loss of profits or revenues, whether incurred
        directly or indirectly, or any loss of data, use, goodwill, or other
        intangible losses, resulting from your use or inability to use our
        service.
      </p>
      <h3 className='font-bold text-xl lg:text-2xl'>Warranty Disclaimer</h3>
      <p className='opacity-80 font-medium'>
        The service is provided &quot;as is&quot; and without warranty of any
        kind, either express or implied, including but not limited to the
        implied warranties of merchantability, fitness for a particular purpose,
        or non-infringement.
      </p>
      <h3 className='font-bold text-xl lg:text-2xl'>Indemnification</h3>
      <p className='opacity-80 font-medium'>
        You agree to indemnify and hold harmless Howcan, Inc., its affiliates,
        and their respective officers, directors, employees, and agents from and
        against all claims, liabilities, damages, losses, and expenses,
        including reasonable legal and accounting fees, arising out of or in any
        way connected with your access to or use of the Service or your
        violation of these Terms of Use.
      </p>
      <h3 className='font-bold text-xl lg:text-2xl'>Severability</h3>
      <p className='opacity-80 font-medium'>
        If any provision of these Terms of Use is found to be invalid or
        unenforceable, that provision will be enforced to the maximum extent
        permissible, and the remaining provisions will remain in full force and
        effect.
      </p>
      <h3 className='font-bold text-xl lg:text-2xl'>Entire Agreement</h3>
      <p className='opacity-80 font-medium'>
        These Terms of Use constitute the entire agreement between you and
        Howcan, Inc. and supersede all prior or contemporaneous understandings
        and agreements, whether written or oral, with respect to the service.
      </p>
      <h3 className='font-bold text-xl lg:text-2xl'>
        Links to Third-Party Websites
      </h3>
      <p className='opacity-80 font-medium'>
        Our service may contain links to third-party websites. We are not
        responsible for the content, accuracy, or opinions expressed on such
        websites, and such websites are not investigated, monitored, or checked
        for accuracy or completeness by us.
      </p>
      <h3 className='font-bold text-xl lg:text-2xl'>Updates to These Terms</h3>
      <p className='opacity-80 font-medium'>
        We may update these Terms of Use from time to time. The latest version
        will be posted on our website, and it is your responsibility to review
        these Terms regularly.
      </p>
      <h3 className='font-bold text-xl lg:text-2xl'>Contact Us</h3>
      <p className='opacity-80 font-medium'>
        For any concerns or questions regarding these Terms, you can contact us
        at
        <span className='text-primary'>
          <Link href='mailto:support@howcan.io'>{''} support@howcan.io</Link>
        </span>
        .
      </p>
    </div>
  );
}
